# Generated by Django 3.2.5 on 2021-07-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyEcom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
    ]
