# Generated by Django 3.2.5 on 2021-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEcom', '0004_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('E', 'Electronics'), ('W', 'Watch'), ('C', 'Cream')], max_length=2),
        ),
    ]
