# Generated by Django 3.2.5 on 2021-07-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyEcom', '0006_auto_20210724_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='zip',
        ),
    ]
